/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java */

package com.dw.system.codedom.parser;

public class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(UQLTreeParser p, int id) {
    super(p, id);
  }

}
