/* Generated By:JJTree: Do not edit this line. ASTCodeBlock.java */

package com.dw.system.codedom.parser;

import com.dw.system.codedom.AbstractRunEnvironment;
import com.dw.system.codedom.RunContext;

public class ASTCodeBlock extends SimpleNode
{
	public ASTCodeBlock(int id)
	{
		super(id);
	}

	public ASTCodeBlock(UQLTreeParser p, int id)
	{
		super(p, id);
	}

	public Object runGetValue(AbstractRunEnvironment env, RunContext context)
			throws Exception
	{//安装顺序运行即可
		int cc = this.jjtGetNumChildren();
		if (cc<=0)
			return null;

		for(int i = 0 ; i < cc ; i ++)
		{
			this.jjtGetChild(i).runGetValue(env, context);
		}
		return null;
	}
}
