/* Generated By:JJTree: Do not edit this line. ASTCodeIf.java */

package com.dw.system.codedom.parser;

import com.dw.system.codedom.AbstractRunEnvironment;
import com.dw.system.codedom.RunContext;

public class ASTCodeIf extends SimpleNode
{
	public ASTCodeIf(int id)
	{
		super(id);
	}

	public ASTCodeIf(UQLTreeParser p, int id)
	{
		super(p, id);
	}

	public Object runGetValue(AbstractRunEnvironment env, RunContext context)
			throws Exception
	{
		int cc = this.jjtGetNumChildren() ;
		if(cc<1)
			return null ;
		
		Object o = this.jjtGetChild(0).runGetValue(env, context) ;
		boolean ifok = false;
		if(o!=null)
		{
			if(o instanceof Boolean)
			{
				ifok = (Boolean)o ;
			}
			else
			{
				ifok = true ;
			}
		}
		
		if(cc==2)
		{// only if
			if(ifok)
			{//run if satisify
				this.jjtGetChild(1).runGetValue(env, context) ;
				return null ;
			}
		}
		else if(cc==3)
		{
			if(ifok)
			{//run if satisify
				this.jjtGetChild(1).runGetValue(env, context) ;
				return null ;
			}
			else
			{//run else
				this.jjtGetChild(2).runGetValue(env, context) ;
				return null ;
			}
		}
		return null;
	}
}
