/* Generated By:JJTree: Do not edit this line. ASTName.java */

package com.dw.system.codedom.parser;

public class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(UQLTreeParser p, int id) {
    super(p, id);
  }

}
