/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package com.dw.system.codedom.parser;

public class ASTNullLiteral extends SimpleNode {
  public ASTNullLiteral(int id) {
    super(id);
  }

  public ASTNullLiteral(UQLTreeParser p, int id) {
    super(p, id);
  }

}
