/* Generated By:JJTree: Do not edit this line. ASTNameList.java */

package com.dw.system.codedom.parser;

public class ASTNameList extends SimpleNode {
  public ASTNameList(int id) {
    super(id);
  }

  public ASTNameList(UQLTreeParser p, int id) {
    super(p, id);
  }

}
