/* Generated By:JJTree: Do not edit this line. ASTCondOper.java */

package com.dw.system.codedom.parser;

public class ASTOperCond extends SimpleNode
{
	private String operStr = null;

	public ASTOperCond(int id)
	{
		super(id);
	}

	public ASTOperCond(UQLTreeParser p, int id)
	{
		super(p, id);
	}

	public void setOperStr(String oper_str)
	{
		operStr = oper_str;
	}

	public String getOperStr()
	{
		return operStr;
	}

	@Override
	public String toString()
	{
		return UQLTreeParserTreeConstants.jjtNodeName[id] + ":" + operStr;
	}
}
