/* Generated By:JJTree: Do not edit this line. ASTVarDeclarator.java */

package com.dw.system.codedom.parser;

public class ASTVarDeclarator extends SimpleNode {
  public ASTVarDeclarator(int id) {
    super(id);
  }

  public ASTVarDeclarator(UQLTreeParser p, int id) {
    super(p, id);
  }

}
