/* Generated By:JJTree: Do not edit this line. ASTVar.java */

package com.dw.system.codedom.parser;

import com.dw.system.codedom.RunContext;
import com.dw.system.codedom.AbstractRunEnvironment;
import com.dw.system.codedom.ValWrapper;


public class ASTVar extends SimpleNode
{
	private String varName = null ;
	
	public ASTVar(int id)
	{
		super(id);
	}

	public ASTVar(UQLTreeParser p, int id)
	{
		super(p, id);
	}

	public void setName(String v)
	{
		varName = v ;
	}
	
	public String getName()
	{
		return varName;
	}
	
	public Object runGetValue(AbstractRunEnvironment env,RunContext context)
	throws Exception
	{
		ValWrapper vw = context.getValueWrapper(varName);
		if(vw!=null)
			return vw.val;
		
		return env.callGlobalProp(varName);
		//context.getVarValue(varName);
	}
	
	@Override
	public String toString()
	{
		return super.toString()+":" + varName;
	}
}
