/* Generated By:JJTree: Do not edit this line. UQLTreeParserTreeConstants.java */

package com.dw.system.codedom.parser;

public interface UQLTreeParserTreeConstants
{
  public int JJTNAME = 0;
  public int JJTNAMELIST = 1;
  public int JJTCODEBLOCK = 2;
  public int JJTVOID = 3;
  public int JJTVARDECLARATOR = 4;
  public int JJTCODEIF = 5;
  public int JJTEXP = 6;
  public int JJTEXPFUNC = 7;
  public int JJTEXPPROP = 8;
  public int JJTARGUMENTLIST = 9;
  public int JJTVAR = 10;
  public int JJTOPERCOND = 11;
  public int JJTOPER = 12;
  public int JJTCONST = 13;


  public String[] jjtNodeName = {
    "Name",
    "NameList",
    "CodeBlock",
    "void",
    "VarDeclarator",
    "CodeIf",
    "Exp",
    "ExpFunc",
    "ExpProp",
    "ArgumentList",
    "Var",
    "OperCond",
    "Oper",
    "Const",
  };
}
